environment: production
version: 2021.1.2
copyright: J1 · Copyright © 2021
theme: j1-template
template:
  name: j1
  config: j1_config
language: en
coding: UTF-8
doctype: html
title: J1
slogan: starter
description: |
  Made for Jekyll · Made for Your Web
keywords: >-
  Jekyll, One, Template, Ruby, Asciidoctor, Asciidoc, Bootstrap, Javascript, JS,
  JS3, CSS, CSS3, HTML5, Material, Design
author:
  name: username
  email: username@email.domain
  github: username
  twitter: username
  feedburner: feedname
webmaster:
  email: webmaster@example.domain
robots:
  index: false
  follow: false
brand:
  image: modules/icons/j1/j1-512x512.png
  image_height: 48
  text: Starter Web
  text_color: '#9E9E9E'
favicon:
  image: modules/icons/j1/j1-32x32.ico
  type: image/ico
permalink: pretty
url: ''
baseurl: ''
base_path: ''
protocol: http
host: localhost
port: 40000
timezone: Europe/Berlin
encoding: UTF-8
detach: false
show_dir_listing: false
source: .
destination: _site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
collections_dir: collections
include:
  - .htaccess
exclude:
  - log
  - vendor
  - node_modules
  - utilsrv
  - History.markdown
  - README.md
  - changelog.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - yarn.lock
  - config.ru
  - package-lock.json
  - package.json
  - .sass-cache
  - .vscode
  - .idea
  - '*.ignore'
  - '*.bat'
  - '*.sh'
  - '*.tmp'
  - dot.*
  - '*.txt'
  - '*.log'
  - '*.ppt*'
  - '*.pdf'
  - '*.zip'
  - '*.7z'
  - '*.tgz'
  - '*.tar'
  - '*.a2p'
  - '*.asciidoc'
keep_files: []
safe: false
strict_front_matter: false
sass:
  sass_dir: _sass/scss
  style: expanded
future: true
show_drafts: false
unpublished: false
limit_posts: 1000000
liquid:
  error_mode: warn
plugins:
  - asciidoctor
  - jekyll-asciidoc
  - j1-paginator
markdown: kramdown
markdown_ext: 'markdown,md'
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  syntax_highlighter: rouge
asciidoc_attributes:
  hardbreaks-option: null
  source-highlighter: rouge
  icons: font
  imagesdir: /assets/images
  iconsdir: '{imagesdir}/icons/asciidoc'
asciidoc:
  processor: asciidoctor
  require_front_matter_header: true
  ext: adoc
asciidoctor:
  safe: unsafe
  template_dir: _templates
  attributes:
    hardbreaks-option: null
    source-highlighter: rouge
    icons: font
    imagesdir: /assets/images
    iconsdir: '{imagesdir}/icons/asciidoc'
algolia:
  enabled: false
  application_id: your_application_id
  search_only_api_key: your_searchonly_api_key
  index_name: your_index_name
  extensions_to_index:
    - adoc
  files_to_exclude: []
whitelist:
  - jekyll-asciidoc
excerpt_separator: excerpt__end
collections:
  featured:
    output: true
    permalink: '/collections/:collection/:name/'
  biography:
    output: true
    permalink: '/collections/public/:collection/:name/'
  fantasy:
    output: true
    permalink: '/collections/public/:collection/:name/'
  romance:
    output: true
    permalink: '/collections/public/:collection/:name/'
defaults:
  - scope:
      path: assets/data
    values:
      sitemap: false
  - scope:
      path: assets/themes/j1
    values:
      sitemap: false
  - scope:
      path: pages
      type: pages
    values:
      layout: page
      author: J1 Team
      analytics: false
      advertising: false
      comments: false
      toc: true
      fam_menu_id: page_ctrl_simple
      scrollbar: false
      icons:
        family: MDI
        color: md-blue
        size: 5x
      images:
        dir: /assets/images/pages
      resource_options:
        - toccer:
            collapseDepth: 3
  - scope:
      path: posts/public/featured/_posts
      type: posts
    values:
      layout: post
      author: J1 Team
      analytics: false
      advertising: false
      comments: false
      series: false
      toc: true
      fam_menu_id: page_ctrl_simple
      scrollbar: false
      icons:
        family: MDI
        color: md-blue
        size: 5x
      images:
        dir: /assets/images/collections/blog/featured
      resource_options:
        - toccer:
            collapseDepth: 3
  - scope:
      type: posts
      path: posts/public/series/_posts
    values:
      layout: post
      author: J1 Team
      analytics: false
      advertising: false
      comments: false
      series: true
      toc: true
      fam_menu_id: page_ctrl_simple
      scrollbar: false
      icons:
        family: MDI
        color: md-indigo
        size: 5x
      images:
        dir: /assets/images/collections/blog/series
  - scope:
      type: posts
      path: posts/public/wikipedia/_posts
    values:
      layout: post
      author: Wikipedia
      analytics: false
      advertising: false
      comments: false
      series: false
      toc: true
      fam_menu_id: page_ctrl_simple
      scrollbar: false
      icons:
        family: MDI
        color: md-indigo
        size: 5x
      images:
        category-image: null
        dir: /assets/images/collections/blog/wikipedia
  - scope:
      type: featured
      path: collections/_featured
    values:
      layout: page
      sitemap: false
compress_html:
  enabled: true
  profile: false
  blanklines: false
  comments: []
  startings: []
  clippings: []
  endings: []
  ignore:
    envs: []
